// let str1 = "Abhishek" 
// console.log("str1 -> " + str1);
// console.log("str1.length -> " + str1.length);
// console.log();
s = "My Name is Abhishek Jha. Abhishek is very Intelligent";
console.log("s -> " + s);
let part = s.slice(11, 19);
console.log("slice(11, 19) -> " + part);
console.log();
part = s.slice(-12, -4);
console.log("slice(-12, -4) -> " + part);
console.log("s -> " + s);
console.log();
part = s.substring(11, 19);
console.log("substring(11, 19) -> " + part);
console.log("s -> " + s);
console.log();
part = s.substring(-12, 10);
console.log("substring(-12, 10) -> " + part); 
console.log("s -> " + s);
console.log();
part = s.substr(11, 8);
console.log("substr(11, 8) -> " + part);
console.log();
part = s.substr(-12, 8);
console.log("substr(-12, 8) -> " + part);
console.log();
part = s.replace("Abhishek", "Mohit");
console.log("replace(\"Abhishek\", \"Mohit\") -> " + part);
console.log();
part = s.replaceAll("Abhishek", "Mohit");
console.log("replaceAll(\"Abhishek\", \"Mohit\") -> " + part);
console.log();
part = s.replace("a", "b");
console.log("replace(\"a\", \"b\") -> " + part);
console.log();
part = s.replace(/a/g, "b");
console.log("replace(/a/g, \"b\") -> " + part);
console.log();
part = s.replace(/a/ig, "b");
console.log("replace(/a/ig, \"b\") -> " + part);
console.log();
part = s.replaceAll("a", "b");
console.log("replaceAll(\"a\", \"b\") -> " + part);
console.log();
part = s.toLowerCase();
console.log("toLowerCase() -> " + part);
console.log();
part = s.toUpperCase();
console.log("toUpperCase() -> " + part);
console.log();
part = s.concat(". Abhishek is persuing Btech.");
console.log("concat(\". Abhishek is persuing Btech.\") -> " + part);
console.log();
str = "              Abhishek                     ";
console.log("str -> " + part);
console.log();
part = str.trim();
console.log("str.trim() -> " + part);